# Generated by Django 4.1.2 on 2022-10-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('instituto', models.CharField(max_length=30)),
                ('curso', models.CharField(max_length=30)),
                ('ano', models.PositiveIntegerField()),
                ('rides_as_driver', models.PositiveIntegerField(default=0)),
                ('rides_as_passenger', models.PositiveIntegerField(default=0)),
                ('ranking', models.FloatField(default=0)),
                ('image_path', models.CharField(default='https://i.imgur.com/V4RclNb.png', max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=6)),
                ('brand', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=10)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='riders.rider')),
            ],
        ),
    ]
