# Generated by Django 4.1.2 on 2022-11-06 21:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_passengers', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
                ('ending_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_ending_here', to='riders.location')),
                ('starting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_starting_here', to='riders.location')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Recusado'), (1, 'Em Espera'), (2, 'Aprovado')])),
                ('meeting_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riders.location')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riders.ride')),
            ],
            options={
                'unique_together': {('ride', 'passenger')},
            },
        ),
    ]
