# Generated by Django 4.1.2 on 2022-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_location_ride_passenger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='passenger',
            new_name='rider',
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('ride', 'rider')},
        ),
        migrations.AlterField(
            model_name='passenger',
            name='status',
            field=models.IntegerField(choices=[(0, 'Recusado'), (1, 'Em Espera'), (2, 'Aprovado')], default=1),
        ),
    ]
