# Generated by Django 4.1.3 on 2022-11-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rename_passenger_passenger_rider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='ano',
            new_name='ingress_year',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='image_path',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='rider',
            new_name='driver',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='instituto',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rides_as_driver',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rides_as_passenger',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='telefone',
        ),
        migrations.AddField(
            model_name='rider',
            name='college',
            field=models.CharField(default='USP', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='course',
            field=models.CharField(default='Administração', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='phone_number',
            field=models.CharField(default='99999-9999', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255),
        ),
    ]
